services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: logisticsT-db
    environment:
      POSTGRES_DB: logisticsT_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cicd_net

  # Jenkins CI/CD Controller
  jenkins:
    build: 
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cicd_net
    depends_on:
      - postgres

  # SonarQube Code Quality
  sonarqube:
    image: sonarqube:9.9-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_WEB_JAVA_OPTS=-Xmx512M -Xms512M
      - SONAR_CE_JAVA_OPTS=-Xmx512M -Xms512M
      - SONAR_ES_JAVA_OPTS=-Xmx512M -Xms512M
      - "discovery.type=single-node"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - cicd_net
    depends_on:
      - postgres

  # Keycloak Authentication Server
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: logitrack-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8180
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://posteyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJKbk1MRF80NExnTjJjajVzQWc0YjliWi1ZWk5PZ25vRjI1dXpSSDBzWEQ4In0.eyJleHAiOjE3NjczMzA2NDksImlhdCI6MTc2NzMzMDM0OSwianRpIjoiZDUxNWRmZTktZGE5Zi00NWU5LWIyODEtMWUyNzE0ZGQ3ZTBhIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MTgwL3JlYWxtcy9sb2dpdHJhY2siLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiMDNhMWFhYzAtYmU1Mi00NTg5LWI4NjQtNzc3NzEzZmNkNjE4IiwidHlwIjoiQmVhcmVyIiwiYXpwIjoibG9naXRyYWNrLWFwcCIsInNlc3Npb25fc3RhdGUiOiI2MGNiZjI1My0yNDdmLTQxZmMtYjg1Ny04YTU5ZWFjY2VlMzMiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHA6Ly9sb2NhbGhvc3Q6ODA4MCJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJBRE1JTiIsInVtYV9hdXRob3JpemF0aW9uIiwiZGVmYXVsdC1yb2xlcy1sb2dpdHJhY2siXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJzaWQiOiI2MGNiZjI1My0yNDdmLTQxZmMtYjg1Ny04YTU5ZWFjY2VlMzMiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmFtZSI6IkFkbWluIFVzZXIiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbkBsb2dpdHJhY2suY29tIiwiZ2l2ZW5fbmFtZSI6IkFkbWluIiwiZmFtaWx5X25hbWUiOiJVc2VyIiwiZW1haWwiOiJhZG1pbkBsb2dpdHJhY2suY29tIn0.Em4WGwmQoiMXqJDx0u14Y_Gt2OBvQ2bvqLGg7Y7S8fjjruegZ-_pUA39oV7aQ4x5fFEOGXHdE4TVT1baVJMJ3Np7Zesm9Ooe0JjNTfHeWztHd_mBG-PVL-pumeoPZVu-5-y7TWA0qWI8MVaE-JaBkFo8sy9uwY2uAFyv15g4VOH0Z1f08e6rkNxJgY9iqH77_Dr0fMDud23FbzvawA0hXuu9H8vc2Nr1XS4CamI3PwuGE4JcxXs6PnTTmbMCJoAKVPrwI0RAlLB3zLZQd_dgutZFWASykSTRoVh8wtKI991tn4V60DNEvdQIfsh_xJx3I60XLmDhylu1hUTiWswpowgres:5432/logisticsT_db
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
    ports:
      - "8180:8180"
    command:
      - start-dev
      - --http-port=8180
    networks:
      - cicd_net
    depends_on:
      - postgres

volumes:
  postgres_data:
  jenkins_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  keycloak_data:

networks:
  cicd_net: